[project]
name = 'stx-faucet'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.stxfaucet]
path = 'contracts/stxfaucet.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
